apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources: 
  - namespace.yaml
  - rollout-canary.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  #- scaleObject.yaml  