apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout 
    name: rollout
  minReplicasCount: 2
  maxReplicasCount: 5
  cooldownPeriod: 30
  pollingInterval: 15
  # triggers:
  #   - type: prometheus
  #     metadata:
  #       serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
  #       metricName: http_requests_total
  #       query: sum(rate(http_requests_total{app="gitops"}[2m]))
  #       threshold: "100"     

  advanced:
    horizontalPodAutoscalerConfig:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 75
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies: 
            - type: Pods
              value: 4
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 60
          policies: 
            - type: Percent
              value: 50
              periodSeconds: 60 