apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout 
    name: rollout
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: cpu
      metadata:
        type: Utilization        # se seu operador for >=2.17 pode usar metricType: Utilization
        value: "70"
    - type: memory
      metadata:
        type: Utilization
        value: "75"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 4
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60  