apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-${ENV}
  namespace: argocd
  labels:
    name: gitops-${ENV}
spec:
  project: gitops-${ENV}

  source:
    path: gitops/overlays/${ENV}/result
    repoURL: https://github.com/Platform-Engineer-DA/argocd-projects.git
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: ${ENV}

  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true   
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
  - group: argoproj.io 
    kind: Rollout
    jsonPointers:
    - /spec/replicas 
  - group: apps
    kind: Rollout
    jsonPointers:
    - /spec/replicas
  - group: "*"
    kind: "*"
  revisionHistoryLimit: 10   