apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-${ENV}
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: gitops app ${ENV}
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'