apiVersion: v1 
stringData:
  username: ${GIT_USER}
  passoword: ${GIT_PAT}
  project: gitops
  type: git
  url: https://github.com/Platform-Engineer-DA/argocd-projects.git
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repository-gitops
  namespace: argocd
type: Opaque   