apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stg

resources:
- ../../base

images:
- name: marcoscianci/gitops
  newName: marcoscianci/gitops
  newTag: dev_17810326491


namePrefix: gitops-
nameSuffix: -stg

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: gitops
    app.kubernetes.io/name: gitops
    
patches:
- path: patch-host.yaml
- path: patch-rollouts-labels.yaml