name: GitOps ArgoCD Workflow

on: 
  push:
    branches: [main] 
    paths:
      - 'gitops/**'
      - '.github/workflows/**'

jobs:

    PROJECTS:
        
      runs-on: self-hosted
      permissions:
        contents: write
        
      strategy:
        max-parallel: 1
        fail-fast: false
        matrix:
          project: [ gitops ]
          env:  [ dev, stg, prod ]
          
          include: 
          - env: dev
            environment: dev
            project_root: gitops
            overlay_dir: gitops/overlays
            argocd_path: gitops/argocd-project
          
          - env: stg
            environment: stg
            project_root: gitops
            overlay_dir: gitops/overlays
            argocd_path: gitops/argocd-project
           
          - env: prod
            environment: prod
            project_root: gitops
            overlay_dir: gitops/overlays
            argocd_path: gitops/argocd-project
        
      concurrency:
        group: cd-${{ matrix.project }}-${{ matrix.env }}
        cancel-in-progress: false       
  
      environment: ${{ matrix.environment }}
      
      steps:
    
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persistent-crendentials: false
            
        - name: ArgoCD Project Sync
          uses: Platform-Engineer-DA/central-ci-cd/.github/actions/cd/argocd/minikube_argocd_sync@main
          with:
            GIT_PAT:            ${{ secrets.GIT_PAT }}
            GIT_USER:           ${{ secrets.GIT_USER }} 
            ENV:                ${{ matrix.env }}
            OVERLAY_DIR:        ${{ matrix.overlay_dir }}
            ARGOCD_PATH:        ${{ matrix.argocd_path }}    
            


  